# Generated by Django 5.2.6 on 2025-09-27 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_conversions', models.IntegerField(default=0)),
                ('successful_conversions', models.IntegerField(default=0)),
                ('failed_conversions', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('most_common_tools', models.JSONField(default=list)),
                ('most_common_formats', models.JSONField(default=list)),
                ('most_common_topics', models.JSONField(default=list)),
                ('average_processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ISTVONTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('template_json', models.JSONField(help_text='ISTVON structure with placeholder values')),
                ('category', models.CharField(choices=[('content', 'Content Creation'), ('analysis', 'Data Analysis'), ('coding', 'Code Generation'), ('communication', 'Communication'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Available to all users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_prompt', models.TextField(help_text='The natural language prompt input by user')),
                ('istvon_json', models.JSONField(help_text='The generated ISTVON JSON structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_flag', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_passed', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 'Poor - Needs major improvements'), (2, 'Fair - Some issues'), (3, 'Good - Mostly correct'), (4, 'Very Good - Minor tweaks needed'), (5, 'Excellent - Perfect conversion')], null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('source_data_accuracy', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('tools_appropriateness', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('variables_completeness', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('outcome_specification', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notification_relevance', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('suggested_improvements', models.JSONField(default=dict, help_text='Specific improvements for each component')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prompt_processor.promptconversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='promptconversion',
            index=models.Index(fields=['created_at'], name='prompt_proc_created_1955e9_idx'),
        ),
        migrations.AddIndex(
            model_name='promptconversion',
            index=models.Index(fields=['user', 'created_at'], name='prompt_proc_user_id_98cf83_idx'),
        ),
        migrations.AddIndex(
            model_name='promptconversion',
            index=models.Index(fields=['success_flag'], name='prompt_proc_success_6250ed_idx'),
        ),
    ]
